
set  -g default-terminal "tmux-256color"
set  -g base-index      0
setw -g pane-base-index 0

set -g status-keys vi
set -g mode-keys   vi

set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  24
set  -s escape-time       10
set  -g history-limit     2000

unbind-key C-b
set-option -g prefix C-space
set -ga terminal-overrides ",*256col*:Tc"
set -as terminal-overrides ',*indn@'
set -g status-bg red
set -g status-fg black
bind '"' split-window    -c "#{pane_current_path}"
bind  %   split-window -h -c "#{pane_current_path}"
bind  c   new-window      -c "#{pane_current_path}"
bind -r C-h select-pane -L
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R
bind -r C-y copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -r C-p paste-buffer
